#!/usr/bin/env python3
"""Generate arena ability tag lookup from the checked-in source extract.

The input may be either abilities_full.json's UUID-keyed object rows or the compact
server/data/abilities_tags_source.json mapping of UUID to tag list.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "data" / "abilities_tags_source.json"
DEFAULT_OUT = ROOT / "src" / "arena" / "combat" / "ability_tags.rs"


def normalize(raw: object) -> dict[str, list[int]]:
    if not isinstance(raw, dict):
        raise TypeError("expected a UUID-keyed JSON object")

    out: dict[str, list[int]] = {}
    for uuid, value in raw.items():
        if not isinstance(uuid, str):
            raise TypeError("ability UUID keys must be strings")
        tags = value.get("tags") if isinstance(value, dict) else value
        if tags is None:
            continue
        if not isinstance(tags, list) or not all(isinstance(tag, int) for tag in tags):
            raise TypeError(f"{uuid}: expected tags to be a list of integers")
        if tags:
            out[uuid] = tags
    return dict(sorted(out.items()))


def render(tags: dict[str, list[int]]) -> str:
    lines = [
        "// @generated by server/script/gen_ability_tags.py",
        "// Source: server/data/abilities_tags_source.json",
        "",
        "/// Shipped `LearnableAbility.tags[]` values, keyed by ability UUID.",
        "///",
        "/// Kept outside `gamedata.rs` because that file is generated in the capture repo.",
        "pub fn ability_tags(uuid: &str) -> &'static [u8] {",
        "    match uuid {",
    ]
    for uuid, values in tags.items():
        body = ", ".join(str(value) for value in values)
        lines.append(f'        "{uuid}" => &[{body}],')
    lines.extend(
        [
            "        _ => &[],",
            "    }",
            "}",
            "",
            "pub fn ability_has_tag(uuid: &str, tag: u8) -> bool {",
            "    ability_tags(uuid).contains(&tag)",
            "}",
            "",
            "#[cfg(test)]",
            "mod tests {",
            "    use std::collections::BTreeMap;",
            "",
            "    use super::ability_tags;",
            "",
            '    const SOURCE: &str = include_str!("../../../data/abilities_tags_source.json");',
            "",
            "    #[test]",
            "    fn generated_tags_match_committed_source() {",
            "        let source: BTreeMap<String, Vec<u8>> = serde_json::from_str(SOURCE).unwrap();",
            "        assert_eq!(source.len(), 43);",
            "        for (uuid, tags) in source {",
            "            assert_eq!(ability_tags(&uuid), tags.as_slice(), \"{uuid}\");",
            "        }",
            "    }",
            "",
            "    #[test]",
            "    fn untagged_uuid_returns_empty_list() {",
            '        assert!(ability_tags("09aa3390-8f42-4cd5-a88c-5c94d5e1dd29").is_empty());',
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    tags = normalize(json.loads(args.source.read_text()))
    args.out.write_text(render(tags))


if __name__ == "__main__":
    main()
