//! Loads the capture-derived static game definitions (see
//! `blades_lib::static_data`) from JSON files in the `--static-data` directory at
//! startup. Each file is independently optional: a missing or invalid file logs a
//! warning and leaves that part of [`StaticData`] empty rather than failing the
//! server (the corresponding endpoint then degrades to an empty/default response).
//!
//! The files are generated by `blades-capture/scripts/extract-static-data.py` and
//! committed under `deploy/static/`.

use std::{collections::HashMap, fs::File, io::BufReader, path::Path};

use blades_lib::economy::RewardGrant;
use blades_lib::features::challenges::ChallengeTemplate;
use blades_lib::features::daily_reward::DailyRewardDef;
use blades_lib::features::game_events::EventDef;
use blades_lib::static_data::{
    Announcement, AbyssStaticData, GiftDef, ItemModRecipe, Recipe, ShopBundle, ShopData,
    StaticData,
};
use log::warn;
use serde::de::DeserializeOwned;
use serde_json::{Value, json};
use uuid::Uuid;

/// Read a JSON file into `T`, falling back to `T::default()` (with a warning) if the
/// file is missing or invalid.
fn read_json<T: DeserializeOwned + Default>(path: &Path) -> T {
    match File::open(path) {
        Ok(f) => serde_json::from_reader(BufReader::new(f)).unwrap_or_else(|e| {
            warn!("[static] invalid {path:?}: {e}; using default");
            T::default()
        }),
        Err(e) => {
            warn!("[static] no {path:?}: {e}; using default");
            T::default()
        }
    }
}

pub fn load(dir: &Path) -> StaticData {
    let gifts: Vec<GiftDef> = read_json(&dir.join("gifts.json"));
    let announcements: Vec<Announcement> = read_json(&dir.join("announcements.json"));

    // Served-verbatim catalogs; fall back to the empty wrapper the client expects.
    let mut global_shop_overrides: Value = read_json(&dir.join("global_shop_overrides.json"));
    if global_shop_overrides.is_null() {
        global_shop_overrides = json!({ "globalShopOverrides": {} });
    }
    let mut iap: Value = read_json(&dir.join("iap.json"));
    if iap.is_null() {
        iap = json!({ "fulfillmentOverrides": {} });
    }
    let global_shop_grants: HashMap<Uuid, RewardGrant> =
        read_json(&dir.join("global_shop_grants.json"));
    let challenge_templates: Vec<ChallengeTemplate> = read_json(&dir.join("challenges.json"));
    let daily_rewards: Vec<DailyRewardDef> = read_json(&dir.join("daily_rewards.json"));
    let chest_loots: Vec<RewardGrant> = read_json(&dir.join("chest_loots.json"));
    let game_events: Vec<EventDef> = read_json(&dir.join("game_events.json"));
    let salvage_recipes: HashMap<Uuid, HashMap<Uuid, u64>> =
        read_json(&dir.join("salvage_recipes.json"));
    let shop_data: ShopData = read_json(&dir.join("shops.json"));
    let shop_bundles: HashMap<Uuid, ShopBundle> = read_json(&dir.join("shop_bundles.json"));
    let recipes: HashMap<Uuid, Recipe> = read_json(&dir.join("recipes.json"));
    let item_mod_recipes: HashMap<Uuid, ItemModRecipe> =
        read_json(&dir.join("item_mod_recipes.json"));
    let quest_rewards: HashMap<Uuid, RewardGrant> =
        read_json(&dir.join("quest_rewards.json"));
    let abyss: AbyssStaticData = read_json(&dir.join("abyss.json"));

    StaticData {
        gifts: gifts.into_iter().map(|g| (g.global_gift_id, g)).collect::<HashMap<_, _>>(),
        announcements,
        global_shop_overrides,
        iap,
        global_shop_grants,
        challenge_templates,
        daily_rewards,
        chest_loots,
        game_events,
        salvage_recipes,
        shop_data,
        shop_bundles,
        recipes,
        item_mod_recipes,
        quest_rewards,
        abyss,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// The committed `deploy/static/*.json` must deserialize into the `StaticData`
    /// structs — a no-DB guard that the capture-derived data still matches our types
    /// (e.g. catches an Item that drops `properties`).
    #[test]
    fn committed_static_data_loads_non_empty() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../deploy/static");
        let sd = load(&dir);
        assert!(!sd.gifts.is_empty(), "gifts.json");
        assert!(!sd.announcements.is_empty(), "announcements.json");
        assert!(!sd.global_shop_grants.is_empty(), "global_shop_grants.json");
        assert!(!sd.challenge_templates.is_empty(), "challenges.json");
        assert!(!sd.daily_rewards.is_empty(), "daily_rewards.json");
        assert!(!sd.chest_loots.is_empty(), "chest_loots.json (Item.properties default)");
        assert!(!sd.game_events.is_empty(), "game_events.json");
        assert!(!sd.salvage_recipes.is_empty(), "salvage_recipes.json");
        assert!(!sd.shop_data.by_template.is_empty(), "shops.json byTemplate");
        assert!(sd.shop_data.default.is_some(), "shops.json default");
        assert!(!sd.shop_bundles.is_empty(), "shop_bundles.json");
        assert!(!sd.recipes.is_empty(), "recipes.json");
        assert!(!sd.item_mod_recipes.is_empty(), "item_mod_recipes.json");
        assert!(sd.global_shop_overrides.get("globalShopOverrides").is_some());
        assert!(sd.iap.get("fulfillmentOverrides").is_some());
        assert!(!sd.quest_rewards.is_empty(), "quest_rewards.json");
        assert!(!sd.abyss.fixed_slices.is_empty(), "abyss.json fixedSlices");
        assert!(!sd.abyss.random_pool.is_empty(), "abyss.json randomPool");
    }
}
