//! Loads the capture-derived static game definitions (see
//! `blades_lib::static_data`) from JSON files in the `--static-data` directory at
//! startup. Each file is independently optional: a missing or invalid file logs a
//! warning and leaves that part of [`StaticData`] empty rather than failing the
//! server (the corresponding endpoint then degrades to an empty/default response).
//!
//! The files are generated by `blades-capture/scripts/extract-static-data.py` and
//! committed under `deploy/static/`.

use std::{collections::HashMap, fs::File, io::BufReader, path::Path};

use blades_lib::economy::{Price, RewardGrant};
use blades_lib::features::challenges::ChallengeTemplate;
use blades_lib::features::chests::ChestLootTables;
use blades_lib::features::daily_reward::DailyRewardDef;
use blades_lib::features::game_events::EventDef;
use blades_lib::static_data::{
    Announcement, AbyssStaticData, EventQuestsData, FreeProductIds, GiftDef, ItemModRecipe,
    QuestsDailyData, Recipe, RecipeCraftingTypes, ShopBundle, ShopData, SmithCraftables,
    SmithCraftablesFile, StaticData,
};
use log::warn;
use serde::de::DeserializeOwned;
use serde_json::{Value, json};
use uuid::Uuid;

/// Read a JSON file into a UUID-keyed map, skipping the `_meta` provenance block
/// the APK extractors write and any single row that fails to parse. Without this a
/// `_meta` key makes the WHOLE map fail to deserialize, which silently empties the
/// table — for `shop_bundles.json` that means the merchant lists stock it will not
/// sell, so it is worth being explicit about.
fn read_uuid_map<T: DeserializeOwned>(path: &Path) -> HashMap<Uuid, T> {
    let raw: Value = read_json(path);
    let Some(obj) = raw.as_object() else {
        return HashMap::new();
    };
    let mut out = HashMap::new();
    let mut skipped = 0usize;
    for (key, value) in obj {
        let Ok(id) = Uuid::parse_str(key) else {
            continue; // `_meta` and anything else that is not an id
        };
        match serde_json::from_value::<T>(value.clone()) {
            Ok(parsed) => {
                out.insert(id, parsed);
            }
            Err(_) => skipped += 1,
        }
    }
    if skipped > 0 {
        warn!("[static] {path:?}: skipped {skipped} unparseable row(s)");
    }
    out
}

/// Read a JSON file into `T`, falling back to `T::default()` (with a warning) if the
/// file is missing or invalid.
/// The chest loot corpus, COMPILED INTO the binary.
///
/// WHY THIS IS NOT JUST READ FROM DISK (tracker #141, #152)
///
/// `/data/static` is a bind mount shipped by `deploy/arena.sh static`, a different
/// and manual path from merging code. On 2026-09-16 the static sync ran at 19:31
/// UTC and the new tables were committed at 19:56 — twenty-five minutes later. The
/// box therefore kept the pre-fix file, whose schema is a bare list where the
/// current one is an object, so it did not merely go stale, it stopped PARSING:
///
///     [static] invalid "/data/static/chest_loots.json": invalid value:
///             expected key to be a number in quotes at line 3 column 6; using default
///
/// `using default` is an empty table, and `chests.rs` turns an empty table into
/// `RewardGrant::default()`. Every chest in every quest, job and event opened
/// EMPTY, on the live server, while CI stayed green — because the tests read the
/// repo's copy, not the box's.
///
/// `chest_tiers.json` already took this precedent, and its comment says why in one
/// line: so a missing production bind-mount cannot silently restore the stub.
/// Kept beside the source, NOT referenced out of `deploy/static/`.
///
/// `.dockerignore` excludes `deploy/static/` from the image build context — that
/// directory is the 1.1 GB runtime mirror shipped by `arena.sh static`, and it has
/// no business in a build. An `include_str!` reaching into it compiles locally,
/// where the file is present, and then fails only in the image build:
///
///     error: couldn't read `server/src/../../deploy/static/chest_loots.json`:
///            No such file or directory (os error 2)
///
/// which is after the PR is merged, because the image build runs on `main` and
/// not on pull requests. `blades_lib/src/chest_tiers.json` and
/// `interactable_loot.json` already live inside their crate for this reason.
///
/// `the_built_in_chest_loot_matches_the_shipped_file` pins the two copies
/// together, so the duplication cannot drift.
static CHEST_LOOTS_BUILTIN: &str = include_str!("chest_loots.json");

/// Read a static file, falling back to a copy compiled into the binary.
///
/// The difference from [`read_json`] is the whole point: a missing or corrupt file
/// yields the SHIPPED data, not an empty default. Use it for anything whose empty
/// value is silently wrong rather than obviously broken.
fn read_json_or_builtin<T: DeserializeOwned>(path: &Path, builtin: &'static str) -> T {
    let from_disk = File::open(path)
        .map_err(|e| format!("{e}"))
        .and_then(|f| serde_json::from_reader(BufReader::new(f)).map_err(|e| format!("{e}")));
    match from_disk {
        Ok(v) => v,
        Err(e) => {
            warn!("[static] {path:?} unusable ({e}); falling back to the built-in copy");
            serde_json::from_str(builtin)
                .expect("the built-in copy is committed alongside this code and must parse")
        }
    }
}

fn read_json<T: DeserializeOwned + Default>(path: &Path) -> T {
    match File::open(path) {
        Ok(f) => serde_json::from_reader(BufReader::new(f)).unwrap_or_else(|e| {
            warn!("[static] invalid {path:?}: {e}; using default");
            T::default()
        }),
        Err(e) => {
            warn!("[static] no {path:?}: {e}; using default");
            T::default()
        }
    }
}

/// Product ids that are not UUIDs, are retail's own, and can never be bought again.
///
/// `53c6f124-3603-4100-ba9a-e2fe23969f7p` ends in a `p` where a hex digit belongs.
/// Bethesda authored it that way — the same string appears in
/// `global_shop_overrides.json` — and the capture corpus labels it
/// `DecoOffer_S_Candelabra_2019-02-14 00:00_2019-02-17 23:59`: a Valentine's
/// decoration offer whose four-day window closed on 17 February 2019. Dropping it
/// costs nothing, so it is reported at INFO rather than warned about on every boot.
///
/// An id NOT on this list still warns: that one would be new, and a new dropped id
/// is a hole in the live shop.
const KNOWN_DEAD_PRODUCT_IDS: &[&str] = &["53c6f124-3603-4100-ba9a-e2fe23969f7p"];

pub fn load(dir: &Path) -> StaticData {
    let gifts: Vec<GiftDef> = read_json(&dir.join("gifts.json"));
    let announcements: Vec<Announcement> = read_json(&dir.join("announcements.json"));

    // Served-verbatim catalogs; fall back to the empty wrapper the client expects.
    let mut global_shop_overrides: Value = read_json(&dir.join("global_shop_overrides.json"));
    if global_shop_overrides.is_null() {
        global_shop_overrides = json!({ "globalShopOverrides": {} });
    }
    // Admin-authored windows. Its own file so the replay shift cannot touch it —
    // see `StaticData::global_shop_authored`. Normally empty.
    let mut global_shop_authored: Value = read_json(&dir.join("global_shop_authored.json"));
    if global_shop_authored.is_null() {
        global_shop_authored = json!({ "globalShopOverrides": {} });
    }
    let mut iap: Value = read_json(&dir.join("iap.json"));
    if iap.is_null() {
        iap = json!({ "fulfillmentOverrides": {} });
    }
    let global_shop_grants: HashMap<Uuid, RewardGrant> =
        read_json(&dir.join("global_shop_grants.json"));
    // Missing is fail-closed: without an authoritative price table, paid
    // purchases are rejected instead of falling back to the request's price.
    let global_shop_prices: HashMap<Uuid, Vec<Price>> =
        read_json(&dir.join("global_shop_prices.json"));
    // A missing file leaves the list empty, i.e. nothing is free — the safe
    // direction. Only offers retail itself gave away belong here.
    let global_shop_free: FreeProductIds = read_json(&dir.join("global_shop_free.json"));
    // Latest APK `PlayerLvlOffer_03` products for levels whose full grant was
    // also captured. Missing is safe: leveling still works, with no timed offer.
    let level_up_offers: HashMap<u16, Uuid> = read_json(&dir.join("level_up_offers.json"));
    // A missing file leaves the map empty, i.e. no fallback — purchases keep
    // 404ing exactly as they did before this existed. The safe direction.
    let global_shop_offer_contents = {
        let file = read_json::<blades_lib::static_data::OfferContentsFile>(
            &dir.join("global_shop_offer_contents.json"),
        );
        // Report #93: one non-UUID product id used to fail the whole map, so all 541
        // offers were dropped and only a startup WARN said so. It is tolerated now —
        // but say which ids were dropped, every boot, so a silent hole in the shop is
        // visible rather than inferred from a purchase that 404s.
        //
        // Report #184: that WARN fires on every boot for an id nothing can ever ask
        // for, which reads like a fault the operator should act on. A dropped id only
        // deserves a warning when it could still cost a player a purchase, so the one
        // id we have identified as retail's own dead typo is reported at INFO and
        // anything else still warns.
        let (unexpected, known): (Vec<&String>, Vec<&String>) = file
            .unparseable_ids
            .iter()
            .partition(|id| !KNOWN_DEAD_PRODUCT_IDS.contains(&id.as_str()));
        if !unexpected.is_empty() {
            log::warn!(
                "[static] global_shop_offer_contents.json: {} offer(s) loaded, {} skipped \
                 for an unparseable product id: {:?}",
                file.offers.len(),
                unexpected.len(),
                unexpected,
            );
        }
        if !known.is_empty() {
            log::info!(
                "[static] global_shop_offer_contents.json: {} offers loaded; {} known dead \
                 product id(s) skipped: {:?}",
                file.offers.len(),
                known.len(),
                known,
            );
        }
        if file.unparseable_ids.is_empty() {
            log::info!(
                "[static] global_shop_offer_contents.json: {} offers loaded",
                file.offers.len()
            );
        }
        file.offers
    };
    let challenge_templates: Vec<ChallengeTemplate> = read_json(&dir.join("challenges.json"));
    let daily_rewards: Vec<DailyRewardDef> = read_json(&dir.join("daily_rewards.json"));
    let chest_loots: ChestLootTables =
        read_json_or_builtin(&dir.join("chest_loots.json"), CHEST_LOOTS_BUILTIN);
    let game_events: Vec<EventDef> = read_json(&dir.join("game_events.json"));
    let salvage_recipes: HashMap<Uuid, HashMap<Uuid, u64>> =
        read_json(&dir.join("salvage_recipes.json"));
    let shop_data: ShopData = read_json(&dir.join("shops.json"));
    let shop_bundles: HashMap<Uuid, ShopBundle> = read_uuid_map(&dir.join("shop_bundles.json"));
    let recipes: HashMap<Uuid, Recipe> = read_json(&dir.join("recipes.json"));
    let item_mod_recipes: HashMap<Uuid, ItemModRecipe> =
        read_json(&dir.join("item_mod_recipes.json"));
    // The APK-extracted recipe -> CraftingType table. A missing file degrades to an
    // empty map and the craft path keeps its captured-recipe / smith / alchemy fallback
    // chain — the same behaviour as before the table existed.
    let recipe_crafting_types: RecipeCraftingTypes =
        read_json(&dir.join("recipe_crafting_types.json"));
    // `read_uuid_map`, not `read_json`: the file carries a `_meta` provenance block
    // (coverage, the list of quests no capture covers, where the numbers came from).
    // Through `read_json` a single non-UUID key fails the WHOLE map and every quest
    // silently pays nothing — the exact silent-emptying failure `read_uuid_map`
    // exists to prevent.
    let quest_rewards: HashMap<Uuid, RewardGrant> =
        read_uuid_map(&dir.join("quest_rewards.json"));
    let abyss: AbyssStaticData = read_json(&dir.join("abyss.json"));
    // The forge craftables file has a rich schema; deserialize the raw shape and resolve
    // it into by-recipe / by-template lookups (a missing file → empty lookups, and the
    // smith craft keeps its lenient placeholder path rather than failing).
    let smith_craftables_raw: SmithCraftablesFile =
        read_json(&dir.join("smith_craftables.json"));
    let smith_craftables = SmithCraftables::from_raw(smith_craftables_raw);
    let quests_daily: QuestsDailyData = read_json(&dir.join("quests_daily.json"));
    let event_quests: EventQuestsData = read_json(&dir.join("event_quests.json"));

    StaticData {
        gifts: gifts.into_iter().map(|g| (g.global_gift_id, g)).collect::<HashMap<_, _>>(),
        announcements,
        global_shop_overrides,
        global_shop_authored,
        iap,
        global_shop_grants,
        global_shop_prices,
        global_shop_free,
        level_up_offers,
        global_shop_offer_contents,
        challenge_templates,
        daily_rewards,
        chest_loots,
        game_events,
        salvage_recipes,
        shop_data,
        shop_bundles,
        recipes,
        item_mod_recipes,
        recipe_crafting_types,
        quest_rewards,
        abyss,
        smith_craftables,
        quests_daily,
        event_quests,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// The committed `deploy/static/*.json` must deserialize into the `StaticData`
    /// structs — a no-DB guard that the capture-derived data still matches our types
    /// (e.g. catches an Item that drops `properties`).
    /// Report #189 (Mɾʂιɾι): "Make seasonal festivities work again, Halloween,
    /// Christmas themes."
    ///
    /// The holiday event quests — EQ40 *Season of the Witch* and EQ42 *The Long
    /// Night* — exist in the shipped game data but were retired before our capture
    /// corpus begins, so they were absent from `game_events.json` and simply never
    /// ran. This asserts the CALENDAR, against the real committed file: an identity
    /// test, not a shape test. A seasonal event that loads, parses and never opens
    /// on the holiday would pass every count assertion above and still deliver
    /// nothing.
    ///
    /// It also pins the thing a 365-day period gets wrong: leap years pull each
    /// instance a day earlier, so the window has to be wide enough to absorb the
    /// drift for the life of the server, not just in its anchor year.
    #[test]
    fn the_holiday_events_open_on_their_holidays_and_stay_shut_otherwise() {
        use blades_lib::features::game_events::active_events;
        use uuid::uuid;

        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../deploy/static");
        let sd = load(&dir);

        const WITCH: uuid::Uuid = uuid!("f116b952-9932-4b1a-b20d-246ca2945bb4");
        const LONG_NIGHT: uuid::Uuid = uuid!("b82b5384-5d68-4703-9450-1815f6d7d28b");

        // Midnight UTC on a given day, without pulling in a date crate.
        const DAY: i64 = 86_400;
        let day = |epoch_of_2026_01_01_plus: i64| 1_767_225_600 + epoch_of_2026_01_01_plus * DAY;
        let open_on = |d: i64, quest: uuid::Uuid| {
            active_events(&sd.game_events, day(d))
                .iter()
                .any(|e| e.quest_id == quest)
        };

        // 2026: 31 Oct is day 303, 25 Dec is day 358, 15 Jun is day 165.
        assert!(open_on(303, WITCH), "Season of the Witch must run at Halloween");
        assert!(open_on(358, LONG_NIGHT), "The Long Night must run at midwinter");

        // …and nowhere else. Midsummer is the control: if these were simply always
        // open, every assertion above would still pass.
        assert!(!open_on(165, WITCH), "Season of the Witch must not run in June");
        assert!(!open_on(165, LONG_NIGHT), "The Long Night must not run in June");
        assert!(!open_on(358, WITCH), "Halloween event open at Christmas");
        assert!(!open_on(303, LONG_NIGHT), "midwinter event open at Halloween");

        // Four years on, after a leap day has shifted the 365-day series a day
        // earlier, both must still cover their holiday.
        let four_years = 365 * 4 + 1;
        assert!(
            open_on(303 + four_years, WITCH),
            "leap drift pushed Season of the Witch off Halloween"
        );
        assert!(
            open_on(358 + four_years, LONG_NIGHT),
            "leap drift pushed The Long Night off Christmas"
        );

        // The rotation is untouched: the daily/Sigil events still deliver retail's
        // expected 1-2 open at an arbitrary moment in June.
        let midsummer = active_events(&sd.game_events, day(165)).len();
        assert!(
            (1..=2).contains(&midsummer),
            "the 39-day rotation now shows {midsummer} events at midsummer, not 1-2"
        );
    }

    /// Report #141: "chests in the store still load the same loot". The old pool was
    /// a flat 40-bundle list keyed only by chest id, so a tier-1 and a tier-5 chest
    /// could draw the same bundle and a chest's level changed nothing. Assert the
    /// committed data now separates them on BOTH axes.
    #[test]
    fn committed_chest_loot_varies_by_tier_and_level() {
        use blades_lib::economy::GOLD;
        use blades_lib::features::chests::pick_loot;

        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../deploy/static");
        let sd = load(&dir);

        // Same chest id and level, different tier -> different, richer loot.
        let gold_at = |tier: u64, level: u64| {
            pick_loot(&sd.chest_loots, tier, level, "chest-1")
                .unwrap_or_else(|| panic!("no loot for tier {tier}"))
                .currencies
                .get(&GOLD)
                .copied()
                .unwrap_or(0)
        };
        let by_tier: Vec<u64> = (1..=5).map(|t| gold_at(t, 50)).collect();
        for (tier, pair) in by_tier.windows(2).enumerate() {
            assert!(
                pair[1] > pair[0],
                "tier {} paid {} but tier {} paid {} — chest tier must raise the gold",
                tier + 1,
                pair[0],
                tier + 2,
                pair[1]
            );
        }

        // Same chest id and tier, different level -> different loot. Retail scaled
        // chest contents with the chest's level; a flat pool did not.
        for tier in 1..=3u64 {
            assert_ne!(
                gold_at(tier, 1),
                gold_at(tier, 100),
                "tier {tier} pays the same at chest level 1 and 100"
            );
        }
    }

    #[test]
    fn committed_static_data_loads_non_empty() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../deploy/static");
        let sd = load(&dir);
        assert!(!sd.gifts.is_empty(), "gifts.json");
        assert!(!sd.announcements.is_empty(), "announcements.json");
        assert!(!sd.global_shop_grants.is_empty(), "global_shop_grants.json");
        assert!(!sd.global_shop_prices.is_empty(), "global_shop_prices.json");
        assert!(
            sd.level_up_offers.len() >= 10,
            "level_up_offers.json latest grantable APK offers"
        );
        for (level, product_id) in &sd.level_up_offers {
            assert!(
                sd.global_shop_prices.contains_key(product_id),
                "level {level} offer {product_id} has no authoritative price"
            );
            assert!(
                sd.global_shop_grants.contains_key(product_id),
                "level {level} offer {product_id} cannot be fulfilled"
            );
        }
        let gems: Uuid = "470c8f58-a8dd-4c07-8c92-843b785e1139".parse().unwrap();
        for (id, quantity) in [
            ("0e224ca0-1506-490f-884a-8871ffe6399b", 250),
            ("7bf00a9c-6a08-4b55-a60d-53915baa38a3", 750),
            ("1275d959-bbe5-460d-8f6a-1c31106a8eb2", 2500),
        ] {
            let prices = &sd.global_shop_prices[&id.parse().unwrap()];
            assert_eq!(prices, &[Price::new(gems, quantity)], "APK price for {id}");
        }
        assert!(!sd.challenge_templates.is_empty(), "challenges.json");
        assert!(!sd.daily_rewards.is_empty(), "daily_rewards.json");
        // Retail's daily reward is weekday-keyed (Tuesday is always Clay), so the
        // committed pool must claim all seven days exactly once. Without this the
        // pool silently falls back to position rotation and every reward lands on
        // the wrong day — which is what it did before the weekday field existed.
        let mut days: Vec<u8> = sd.daily_rewards.iter().filter_map(|d| d.weekday).collect();
        days.sort_unstable();
        assert_eq!(days, (0u8..7).collect::<Vec<_>>(), "daily_rewards.json weekdays");
        assert!(!sd.chest_loots.is_empty(), "chest_loots.json (Item.properties default)");

        // Tiers 1-3 are the ones retail capture covers well enough to publish; a
        // silently tier-less file is exactly the regression that made every chest
        // pay the same bundle (#141).
        for tier in 1..=3u64 {
            let pool = sd.chest_loots.tiers.get(&tier);
            assert!(
                pool.is_some_and(|p| p.len() >= 100),
                "chest_loots.json tier {tier} pool"
            );
        }
        // Tiers 4 and 5 are too thinly captured to be tables, but they must still
        // have loot of their OWN: without it `pick_loot` silently hands a tier-5
        // chest the tier-3 table, which is the bug this file was rebuilt to fix.
        for tier in 1..=5u64 {
            assert!(
                sd.chest_loots.has_own_pool(tier),
                "chest_loots.json has no pool of its own for tier {tier}"
            );
        }
        assert!(!sd.game_events.is_empty(), "game_events.json");
        assert!(!sd.salvage_recipes.is_empty(), "salvage_recipes.json");
        assert!(!sd.shop_data.by_template.is_empty(), "shops.json byTemplate");
        assert!(sd.shop_data.default.is_some(), "shops.json default");
        assert!(!sd.shop_bundles.is_empty(), "shop_bundles.json");
        assert!(!sd.recipes.is_empty(), "recipes.json");
        assert!(!sd.item_mod_recipes.is_empty(), "item_mod_recipes.json");
        // The APK-extracted recipe -> CraftingType table. Every recipe the client ships
        // is in here, so a craft job can always name a real bench instead of guessing.
        assert!(
            !sd.recipe_crafting_types.recipes.is_empty(),
            "recipe_crafting_types.json recipes"
        );
        assert_eq!(
            sd.recipe_crafting_types.crafting_types.len(),
            7,
            "recipe_crafting_types.json craftingTypes (the client ships exactly 7)"
        );
        // Every captured recipe must agree with the APK on which bench it belongs to —
        // this is the cross-check that the extraction is reading the right pointer. It
        // held for all 34 committed rows at extraction time.
        for (id, recipe) in &sd.recipes {
            if let Some(from_apk) = sd.recipe_crafting_types.crafting_type_of(id) {
                assert_eq!(
                    recipe.crafting_type_id, from_apk,
                    "recipes.json {id} disagrees with the APK crafting type"
                );
            }
        }
        assert!(sd.global_shop_overrides.get("globalShopOverrides").is_some());
        assert!(sd.iap.get("fulfillmentOverrides").is_some());
        assert!(!sd.quest_rewards.is_empty(), "quest_rewards.json");
        assert!(!sd.abyss.fixed_slices.is_empty(), "abyss.json fixedSlices");
        assert!(!sd.abyss.random_pool.is_empty(), "abyss.json randomPool");
        // New abyss keys wire in.
        assert!(!sd.abyss.difficulty_curve.is_empty(), "abyss.json difficultyCurve");
        assert!(!sd.abyss.monster_tiers.is_empty(), "abyss.json monsterTiers");
        assert!(!sd.abyss.depth_bands.is_empty(), "abyss.json depthBands");
        assert!(!sd.abyss.dungeon_pool.is_empty(), "abyss.json dungeonPool");
        // Smith craftables resolve into both lookups + carry the smithing type id.
        assert!(!sd.smith_craftables.by_template.is_empty(), "smith_craftables.json byTemplate");
        assert!(!sd.smith_craftables.by_recipe.is_empty(), "smith_craftables.json byRecipe (captured)");
        assert!(
            sd.smith_craftables.smithing_crafting_type_id.is_some(),
            "smith_craftables.json smithingCraftingTypeId"
        );
        // Daily quests: pool + non-dungeon exclusion list + a scaling table.
        assert!(!sd.quests_daily.daily_quest_pool.is_empty(), "quests_daily.json dailyQuestPool");
        assert!(!sd.quests_daily.non_dungeon_quests.is_empty(), "quests_daily.json nonDungeonQuests");
        assert!(
            !sd.quests_daily.level_scaling.enemy_level_from_player_level.offset_by_skull.is_empty(),
            "quests_daily.json levelScaling"
        );
        // The event calendar and its milestone tables must both survive the load, and
        // must agree with each other — an event whose template is missing would
        // advertise a Sigil quest that pays nothing.
        // 39 capture-derived events on the 39-day rotation, plus the SEVEN
        // authored ones restored for #189 (Mɾʂιɾι: "make seasonal festivities work
        // again") — five back on the rotation, two on a calendar date. Counting is
        // not the point; the split is, so assert on the recurrence period too.
        assert_eq!(sd.game_events.len(), 46, "game_events.json");
        assert_eq!(sd.event_quests.templates.len(), 46, "event_quests.json");
        let rotating = sd
            .game_events
            .iter()
            .filter(|d| d.recurrence.recurrence_interval == 39)
            .count();
        let annual: Vec<_> = sd
            .game_events
            .iter()
            .filter(|d| d.recurrence.recurrence_interval == 365)
            .collect();
        assert_eq!(rotating, 44, "39 captured + the 5 restored retired events");
        assert_eq!(annual.len(), 2, "the two seasonal events");
        // A seasonal event that opened for two days like the rotation ones would be a
        // silent regression — the whole point is a holiday-length window.
        for d in &annual {
            assert!(
                d.window_secs() >= 8 * 86_400,
                "seasonal event {} opens for only {}s",
                d.event_id,
                d.window_secs()
            );
        }
        for def in &sd.game_events {
            assert!(
                sd.event_quests.templates.contains_key(&def.quest_id),
                "event {} has no milestone table",
                def.event_id
            );
        }
        // `quest_rewards.json` carries a `_meta` block. Read through `read_json` a
        // single non-UUID key fails the WHOLE map, so this count is what proves the
        // table is being read with `read_uuid_map` and is not silently empty.
        assert!(
            sd.quest_rewards.len() > 150,
            "quest_rewards.json loaded only {} entries — is _meta emptying it?",
            sd.quest_rewards.len()
        );
    }

    /// The capture-derived `global_shop_grants.json` carries retail's per-item `grade`
    /// and `arcaneTier`, and until `Item` had fields for them serde threw both on the
    /// floor on load — silently, because `Item` cannot use `deny_unknown_fields` (it is
    /// `flatten`ed by `RewardItem`). The file was right; the struct was lossy.
    ///
    /// This asserts against the REAL committed file rather than a fixture, so it fails if
    /// the fields are removed from `Item`, if the flatten path stops carrying them, or if
    /// a future re-extraction drops them from the data.
    #[test]
    fn committed_grants_keep_retail_grade_and_arcane_tier() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../deploy/static");
        let sd = load(&dir);

        let graded = sd
            .global_shop_grants
            .values()
            .flat_map(|g| &g.items)
            .filter(|i| i.item.grade.is_some())
            .count();
        let arcane = sd
            .global_shop_grants
            .values()
            .flat_map(|g| &g.items)
            .filter(|i| i.item.arcane_tier.is_some())
            .count();
        // Counts as committed at the time of writing. They are lower bounds: a
        // re-extraction may add more, but going DOWN means the plumbing broke.
        assert!(graded >= 8, "global_shop_grants.json lost item grades (found {graded})");
        assert!(arcane >= 19, "global_shop_grants.json lost item arcaneTiers (found {arcane})");

        // The one grant that carries BOTH, pinned by id so the values are checked and not
        // just counted.
        let id: Uuid = "79995d29-eac2-49a3-bfec-ce9e547b98de".parse().unwrap();
        let grant = sd.global_shop_grants.get(&id).expect("grant 79995d29 present");
        let item = grant
            .items
            .iter()
            .find(|i| i.item.grade.is_some())
            .expect("grant 79995d29 has a graded item");
        assert_eq!(item.item.grade, Some(4), "grant 79995d29 item grade");
        assert_eq!(item.item.arcane_tier, Some(2), "grant 79995d29 item arcaneTier");
        // Retail's graded items carry GRADING affixes and no tempering/durability.
        assert!(!item.item.properties.grading.is_empty(), "graded item keeps its GRADING affixes");
    }

    /// A CORRUPT OR MISSING `chest_loots.json` MUST NOT EMPTY EVERY CHEST.
    ///
    /// This is not hypothetical. On 2026-09-16 the live server logged
    ///
    ///     [static] invalid "/data/static/chest_loots.json": invalid value:
    ///             expected key to be a number in quotes at line 3 column 6; using default
    ///
    /// because the box's bind-mounted copy predated the schema change — the static
    /// sync ran 25 minutes before the commit that changed it. `using default` is an
    /// empty table, and `chests.rs` turns that into an empty reward, so every chest
    /// in every quest, job and event opened with nothing in it. CI never saw it: the
    /// other tests read the repo's file, not the box's.
    #[test]
    fn a_broken_chest_loot_file_falls_back_to_the_built_in_corpus() {
        let dir = std::env::temp_dir().join(format!("nb-chest-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();

        // Exactly the shape that failed in production: the OLD schema, a bare list.
        let path = dir.join("chest_loots.json");
        std::fs::write(&path, "[\n  {\n   \"id\": 1\n  }\n]").unwrap();
        let from_corrupt: ChestLootTables = read_json_or_builtin(&path, CHEST_LOOTS_BUILTIN);
        assert!(
            !from_corrupt.is_empty(),
            "a corrupt file must fall back to the shipped corpus, not to an empty table"
        );

        // …and so must an absent one.
        std::fs::remove_file(&path).unwrap();
        let from_missing: ChestLootTables = read_json_or_builtin(&path, CHEST_LOOTS_BUILTIN);
        assert!(!from_missing.is_empty(), "a missing file must fall back too");

        // THE CONTROL: the fallback is not masking a broken built-in. The corpus
        // compiled in must carry the same per-tier depth the on-disk assertions
        // demand, or "not empty" would be satisfied by a one-entry stub.
        for tier in 1..=3u64 {
            let pool = from_missing.tiers.get(&tier);
            assert!(
                pool.is_some_and(|p| p.len() >= 100),
                "built-in corpus tier {tier} is thin or absent"
            );
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    /// The built-in copy and the shipped file must stay identical.
    ///
    /// Two copies exist because the bind-mounted `deploy/static/` is excluded from
    /// the image build context, so the compiled-in fallback has to live beside the
    /// source. That duplication is only safe if drift is impossible, which is what
    /// this asserts — byte for byte, not merely "both parse".
    #[test]
    fn the_built_in_chest_loot_matches_the_shipped_file() {
        let shipped = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../deploy/static/chest_loots.json");
        let shipped = std::fs::read_to_string(&shipped)
            .unwrap_or_else(|e| panic!("cannot read {shipped:?}: {e}"));
        assert_eq!(
            shipped.len(),
            CHEST_LOOTS_BUILTIN.len(),
            "deploy/static/chest_loots.json and server/src/chest_loots.json differ in length"
        );
        assert!(
            shipped == CHEST_LOOTS_BUILTIN,
            "deploy/static/chest_loots.json and server/src/chest_loots.json have drifted; \
             copy the shipped file over the built-in one"
        );
    }

    /// THE SECOND CONTROL: a GOOD file on disk still wins. The fallback must not
    /// have quietly replaced the bind mount — that would make shipping new loot
    /// tables via `arena.sh static` impossible.
    #[test]
    fn a_valid_chest_loot_file_on_disk_is_preferred() {
        let dir = std::env::temp_dir().join(format!("nb-chest-ok-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("chest_loots.json");
        // A minimal but VALID document, distinguishable from the built-in by size.
        std::fs::write(&path, r#"{"tiers":{},"provisionalTiers":{}}"#).unwrap();

        let loaded: ChestLootTables = read_json_or_builtin(&path, CHEST_LOOTS_BUILTIN);
        assert!(
            loaded.tiers.is_empty(),
            "a parseable file on disk must be used verbatim, even when it is thinner \
             than the built-in copy — otherwise arena.sh static could never ship an update"
        );
        std::fs::remove_dir_all(&dir).ok();
    }
}

#[cfg(test)]
mod known_dead_product_id_tests {
    use super::KNOWN_DEAD_PRODUCT_IDS;

    /// Every entry must actually be unparseable. A parseable id would never reach
    /// `unparseable_ids`, so it would sit here silencing nothing while looking like
    /// it did — and the next genuinely broken id would be the one to go quiet.
    #[test]
    fn every_known_dead_id_is_really_unparseable() {
        for id in KNOWN_DEAD_PRODUCT_IDS {
            assert!(
                uuid::Uuid::parse_str(id).is_err(),
                "{id} parses as a UUID, so listing it here silences nothing"
            );
        }
    }

    /// The list is an allowlist for *known* breakage, so it stays short and explicit.
    /// Growing it is a decision, not a reflex: a second entry means a second offer the
    /// live shop cannot sell.
    #[test]
    fn the_list_holds_only_the_one_retail_typo() {
        assert_eq!(
            KNOWN_DEAD_PRODUCT_IDS,
            &["53c6f124-3603-4100-ba9a-e2fe23969f7p"]
        );
    }
}
