//! Loads the capture-derived static game definitions (see
//! `blades_lib::static_data`) from JSON files in the `--static-data` directory at
//! startup. Each file is independently optional: a missing or invalid file logs a
//! warning and leaves that part of [`StaticData`] empty rather than failing the
//! server (the corresponding endpoint then degrades to an empty/default response).
//!
//! The files are generated by `blades-capture/scripts/extract-static-data.py` and
//! committed under `deploy/static/`.

use std::{collections::HashMap, fs::File, io::BufReader, path::Path};

use blades_lib::economy::{Price, RewardGrant};
use blades_lib::features::challenges::ChallengeTemplate;
use blades_lib::features::daily_reward::DailyRewardDef;
use blades_lib::features::game_events::EventDef;
use blades_lib::static_data::{
    Announcement, AbyssStaticData, EventQuestsData, FreeProductIds, GiftDef, ItemModRecipe,
    QuestsDailyData, Recipe, RecipeCraftingTypes, ShopBundle, ShopData, SmithCraftables,
    SmithCraftablesFile, StaticData,
};
use log::warn;
use serde::de::DeserializeOwned;
use serde_json::{Value, json};
use uuid::Uuid;

/// Read a JSON file into a UUID-keyed map, skipping the `_meta` provenance block
/// the APK extractors write and any single row that fails to parse. Without this a
/// `_meta` key makes the WHOLE map fail to deserialize, which silently empties the
/// table — for `shop_bundles.json` that means the merchant lists stock it will not
/// sell, so it is worth being explicit about.
fn read_uuid_map<T: DeserializeOwned>(path: &Path) -> HashMap<Uuid, T> {
    let raw: Value = read_json(path);
    let Some(obj) = raw.as_object() else {
        return HashMap::new();
    };
    let mut out = HashMap::new();
    let mut skipped = 0usize;
    for (key, value) in obj {
        let Ok(id) = Uuid::parse_str(key) else {
            continue; // `_meta` and anything else that is not an id
        };
        match serde_json::from_value::<T>(value.clone()) {
            Ok(parsed) => {
                out.insert(id, parsed);
            }
            Err(_) => skipped += 1,
        }
    }
    if skipped > 0 {
        warn!("[static] {path:?}: skipped {skipped} unparseable row(s)");
    }
    out
}

/// Read a JSON file into `T`, falling back to `T::default()` (with a warning) if the
/// file is missing or invalid.
fn read_json<T: DeserializeOwned + Default>(path: &Path) -> T {
    match File::open(path) {
        Ok(f) => serde_json::from_reader(BufReader::new(f)).unwrap_or_else(|e| {
            warn!("[static] invalid {path:?}: {e}; using default");
            T::default()
        }),
        Err(e) => {
            warn!("[static] no {path:?}: {e}; using default");
            T::default()
        }
    }
}

pub fn load(dir: &Path) -> StaticData {
    let gifts: Vec<GiftDef> = read_json(&dir.join("gifts.json"));
    let announcements: Vec<Announcement> = read_json(&dir.join("announcements.json"));

    // Served-verbatim catalogs; fall back to the empty wrapper the client expects.
    let mut global_shop_overrides: Value = read_json(&dir.join("global_shop_overrides.json"));
    if global_shop_overrides.is_null() {
        global_shop_overrides = json!({ "globalShopOverrides": {} });
    }
    // Admin-authored windows. Its own file so the replay shift cannot touch it —
    // see `StaticData::global_shop_authored`. Normally empty.
    let mut global_shop_authored: Value = read_json(&dir.join("global_shop_authored.json"));
    if global_shop_authored.is_null() {
        global_shop_authored = json!({ "globalShopOverrides": {} });
    }
    let mut iap: Value = read_json(&dir.join("iap.json"));
    if iap.is_null() {
        iap = json!({ "fulfillmentOverrides": {} });
    }
    let global_shop_grants: HashMap<Uuid, RewardGrant> =
        read_json(&dir.join("global_shop_grants.json"));
    // Missing is fail-closed: without an authoritative price table, paid
    // purchases are rejected instead of falling back to the request's price.
    let global_shop_prices: HashMap<Uuid, Vec<Price>> =
        read_json(&dir.join("global_shop_prices.json"));
    // A missing file leaves the list empty, i.e. nothing is free — the safe
    // direction. Only offers retail itself gave away belong here.
    let global_shop_free: FreeProductIds = read_json(&dir.join("global_shop_free.json"));
    // A missing file leaves the map empty, i.e. no fallback — purchases keep
    // 404ing exactly as they did before this existed. The safe direction.
    let global_shop_offer_contents = {
        let file = read_json::<blades_lib::static_data::OfferContentsFile>(
            &dir.join("global_shop_offer_contents.json"),
        );
        // Report #93: one non-UUID product id used to fail the whole map, so all 541
        // offers were dropped and only a startup WARN said so. It is tolerated now —
        // but say which ids were dropped, at WARN, every boot, so a silent hole in
        // the shop is visible rather than inferred from a purchase that 404s.
        if !file.unparseable_ids.is_empty() {
            log::warn!(
                "[static] global_shop_offer_contents.json: {} offer(s) loaded, {} skipped \
                 for an unparseable product id: {:?}",
                file.offers.len(),
                file.unparseable_ids.len(),
                file.unparseable_ids,
            );
        } else {
            log::info!(
                "[static] global_shop_offer_contents.json: {} offers loaded",
                file.offers.len()
            );
        }
        file.offers
    };
    let challenge_templates: Vec<ChallengeTemplate> = read_json(&dir.join("challenges.json"));
    let daily_rewards: Vec<DailyRewardDef> = read_json(&dir.join("daily_rewards.json"));
    let chest_loots: Vec<RewardGrant> = read_json(&dir.join("chest_loots.json"));
    let game_events: Vec<EventDef> = read_json(&dir.join("game_events.json"));
    let salvage_recipes: HashMap<Uuid, HashMap<Uuid, u64>> =
        read_json(&dir.join("salvage_recipes.json"));
    let shop_data: ShopData = read_json(&dir.join("shops.json"));
    let shop_bundles: HashMap<Uuid, ShopBundle> = read_uuid_map(&dir.join("shop_bundles.json"));
    let recipes: HashMap<Uuid, Recipe> = read_json(&dir.join("recipes.json"));
    let item_mod_recipes: HashMap<Uuid, ItemModRecipe> =
        read_json(&dir.join("item_mod_recipes.json"));
    // The APK-extracted recipe -> CraftingType table. A missing file degrades to an
    // empty map and the craft path keeps its captured-recipe / smith / alchemy fallback
    // chain — the same behaviour as before the table existed.
    let recipe_crafting_types: RecipeCraftingTypes =
        read_json(&dir.join("recipe_crafting_types.json"));
    // `read_uuid_map`, not `read_json`: the file carries a `_meta` provenance block
    // (coverage, the list of quests no capture covers, where the numbers came from).
    // Through `read_json` a single non-UUID key fails the WHOLE map and every quest
    // silently pays nothing — the exact silent-emptying failure `read_uuid_map`
    // exists to prevent.
    let quest_rewards: HashMap<Uuid, RewardGrant> =
        read_uuid_map(&dir.join("quest_rewards.json"));
    let abyss: AbyssStaticData = read_json(&dir.join("abyss.json"));
    // The forge craftables file has a rich schema; deserialize the raw shape and resolve
    // it into by-recipe / by-template lookups (a missing file → empty lookups, and the
    // smith craft keeps its lenient placeholder path rather than failing).
    let smith_craftables_raw: SmithCraftablesFile =
        read_json(&dir.join("smith_craftables.json"));
    let smith_craftables = SmithCraftables::from_raw(smith_craftables_raw);
    let quests_daily: QuestsDailyData = read_json(&dir.join("quests_daily.json"));
    let event_quests: EventQuestsData = read_json(&dir.join("event_quests.json"));

    StaticData {
        gifts: gifts.into_iter().map(|g| (g.global_gift_id, g)).collect::<HashMap<_, _>>(),
        announcements,
        global_shop_overrides,
        global_shop_authored,
        iap,
        global_shop_grants,
        global_shop_prices,
        global_shop_free,
        global_shop_offer_contents,
        challenge_templates,
        daily_rewards,
        chest_loots,
        game_events,
        salvage_recipes,
        shop_data,
        shop_bundles,
        recipes,
        item_mod_recipes,
        recipe_crafting_types,
        quest_rewards,
        abyss,
        smith_craftables,
        quests_daily,
        event_quests,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// The committed `deploy/static/*.json` must deserialize into the `StaticData`
    /// structs — a no-DB guard that the capture-derived data still matches our types
    /// (e.g. catches an Item that drops `properties`).
    #[test]
    fn committed_static_data_loads_non_empty() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../deploy/static");
        let sd = load(&dir);
        assert!(!sd.gifts.is_empty(), "gifts.json");
        assert!(!sd.announcements.is_empty(), "announcements.json");
        assert!(!sd.global_shop_grants.is_empty(), "global_shop_grants.json");
        assert!(!sd.global_shop_prices.is_empty(), "global_shop_prices.json");
        let gems: Uuid = "470c8f58-a8dd-4c07-8c92-843b785e1139".parse().unwrap();
        for (id, quantity) in [
            ("0e224ca0-1506-490f-884a-8871ffe6399b", 250),
            ("7bf00a9c-6a08-4b55-a60d-53915baa38a3", 750),
            ("1275d959-bbe5-460d-8f6a-1c31106a8eb2", 2500),
        ] {
            let prices = &sd.global_shop_prices[&id.parse().unwrap()];
            assert_eq!(prices, &[Price::new(gems, quantity)], "APK price for {id}");
        }
        assert!(!sd.challenge_templates.is_empty(), "challenges.json");
        assert!(!sd.daily_rewards.is_empty(), "daily_rewards.json");
        // Retail's daily reward is weekday-keyed (Tuesday is always Clay), so the
        // committed pool must claim all seven days exactly once. Without this the
        // pool silently falls back to position rotation and every reward lands on
        // the wrong day — which is what it did before the weekday field existed.
        let mut days: Vec<u8> = sd.daily_rewards.iter().filter_map(|d| d.weekday).collect();
        days.sort_unstable();
        assert_eq!(days, (0u8..7).collect::<Vec<_>>(), "daily_rewards.json weekdays");
        assert!(!sd.chest_loots.is_empty(), "chest_loots.json (Item.properties default)");
        assert!(!sd.game_events.is_empty(), "game_events.json");
        assert!(!sd.salvage_recipes.is_empty(), "salvage_recipes.json");
        assert!(!sd.shop_data.by_template.is_empty(), "shops.json byTemplate");
        assert!(sd.shop_data.default.is_some(), "shops.json default");
        assert!(!sd.shop_bundles.is_empty(), "shop_bundles.json");
        assert!(!sd.recipes.is_empty(), "recipes.json");
        assert!(!sd.item_mod_recipes.is_empty(), "item_mod_recipes.json");
        // The APK-extracted recipe -> CraftingType table. Every recipe the client ships
        // is in here, so a craft job can always name a real bench instead of guessing.
        assert!(
            !sd.recipe_crafting_types.recipes.is_empty(),
            "recipe_crafting_types.json recipes"
        );
        assert_eq!(
            sd.recipe_crafting_types.crafting_types.len(),
            7,
            "recipe_crafting_types.json craftingTypes (the client ships exactly 7)"
        );
        // Every captured recipe must agree with the APK on which bench it belongs to —
        // this is the cross-check that the extraction is reading the right pointer. It
        // held for all 34 committed rows at extraction time.
        for (id, recipe) in &sd.recipes {
            if let Some(from_apk) = sd.recipe_crafting_types.crafting_type_of(id) {
                assert_eq!(
                    recipe.crafting_type_id, from_apk,
                    "recipes.json {id} disagrees with the APK crafting type"
                );
            }
        }
        assert!(sd.global_shop_overrides.get("globalShopOverrides").is_some());
        assert!(sd.iap.get("fulfillmentOverrides").is_some());
        assert!(!sd.quest_rewards.is_empty(), "quest_rewards.json");
        assert!(!sd.abyss.fixed_slices.is_empty(), "abyss.json fixedSlices");
        assert!(!sd.abyss.random_pool.is_empty(), "abyss.json randomPool");
        // New abyss keys wire in.
        assert!(!sd.abyss.difficulty_curve.is_empty(), "abyss.json difficultyCurve");
        assert!(!sd.abyss.monster_tiers.is_empty(), "abyss.json monsterTiers");
        assert!(!sd.abyss.depth_bands.is_empty(), "abyss.json depthBands");
        assert!(!sd.abyss.dungeon_pool.is_empty(), "abyss.json dungeonPool");
        // Smith craftables resolve into both lookups + carry the smithing type id.
        assert!(!sd.smith_craftables.by_template.is_empty(), "smith_craftables.json byTemplate");
        assert!(!sd.smith_craftables.by_recipe.is_empty(), "smith_craftables.json byRecipe (captured)");
        assert!(
            sd.smith_craftables.smithing_crafting_type_id.is_some(),
            "smith_craftables.json smithingCraftingTypeId"
        );
        // Daily quests: pool + non-dungeon exclusion list + a scaling table.
        assert!(!sd.quests_daily.daily_quest_pool.is_empty(), "quests_daily.json dailyQuestPool");
        assert!(!sd.quests_daily.non_dungeon_quests.is_empty(), "quests_daily.json nonDungeonQuests");
        assert!(
            !sd.quests_daily.level_scaling.enemy_level_from_player_level.offset_by_skull.is_empty(),
            "quests_daily.json levelScaling"
        );
        // The event calendar and its milestone tables must both survive the load, and
        // must agree with each other — an event whose template is missing would
        // advertise a Sigil quest that pays nothing.
        assert_eq!(sd.game_events.len(), 39, "game_events.json");
        assert_eq!(sd.event_quests.templates.len(), 39, "event_quests.json");
        for def in &sd.game_events {
            assert!(
                sd.event_quests.templates.contains_key(&def.quest_id),
                "event {} has no milestone table",
                def.event_id
            );
        }
        // `quest_rewards.json` carries a `_meta` block. Read through `read_json` a
        // single non-UUID key fails the WHOLE map, so this count is what proves the
        // table is being read with `read_uuid_map` and is not silently empty.
        assert!(
            sd.quest_rewards.len() > 150,
            "quest_rewards.json loaded only {} entries — is _meta emptying it?",
            sd.quest_rewards.len()
        );
    }

    /// The capture-derived `global_shop_grants.json` carries retail's per-item `grade`
    /// and `arcaneTier`, and until `Item` had fields for them serde threw both on the
    /// floor on load — silently, because `Item` cannot use `deny_unknown_fields` (it is
    /// `flatten`ed by `RewardItem`). The file was right; the struct was lossy.
    ///
    /// This asserts against the REAL committed file rather than a fixture, so it fails if
    /// the fields are removed from `Item`, if the flatten path stops carrying them, or if
    /// a future re-extraction drops them from the data.
    #[test]
    fn committed_grants_keep_retail_grade_and_arcane_tier() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../deploy/static");
        let sd = load(&dir);

        let graded = sd
            .global_shop_grants
            .values()
            .flat_map(|g| &g.items)
            .filter(|i| i.item.grade.is_some())
            .count();
        let arcane = sd
            .global_shop_grants
            .values()
            .flat_map(|g| &g.items)
            .filter(|i| i.item.arcane_tier.is_some())
            .count();
        // Counts as committed at the time of writing. They are lower bounds: a
        // re-extraction may add more, but going DOWN means the plumbing broke.
        assert!(graded >= 8, "global_shop_grants.json lost item grades (found {graded})");
        assert!(arcane >= 19, "global_shop_grants.json lost item arcaneTiers (found {arcane})");

        // The one grant that carries BOTH, pinned by id so the values are checked and not
        // just counted.
        let id: Uuid = "79995d29-eac2-49a3-bfec-ce9e547b98de".parse().unwrap();
        let grant = sd.global_shop_grants.get(&id).expect("grant 79995d29 present");
        let item = grant
            .items
            .iter()
            .find(|i| i.item.grade.is_some())
            .expect("grant 79995d29 has a graded item");
        assert_eq!(item.item.grade, Some(4), "grant 79995d29 item grade");
        assert_eq!(item.item.arcane_tier, Some(2), "grant 79995d29 item arcaneTier");
        // Retail's graded items carry GRADING affixes and no tempering/durability.
        assert!(!item.item.properties.grading.is_empty(), "graded item keeps its GRADING affixes");
    }
}
