//! What building in the town costs, takes and pays — the parts retail keeps in
//! the APK rather than in `building_upgrades.json` (tracker #287).
//!
//! Source: `building_construction.json`, generated by
//! `script/extract_building_construction.py` from the client's
//! `BuildingConstructionDataList._districts[0]` and `TownPointsData`. It is
//! compiled into the binary, so merging a change to it ships it (the
//! `deploy/static` bind mount does not ride along with a merge).
//!
//! The rules, each measured against retail:
//!
//! * **Placing** the (n+1)-th building of a family costs `constructionGold[n]`
//!   (plus the chosen style's gold) and takes `constructionMs[n]`, where n
//!   counts the family's buildings standing in the town in any state. The
//!   three house types are one family; every other type is its own. 49 of 50
//!   captured placement timers and every clean placement debit agree.
//! * **Upgrading** to level L costs `upgradeGold[L]` (plus the worn style's
//!   gold) and takes `upgradeMs[L]`.
//! * **Destroying** costs `destructionGold[n]`, n again counting the family
//!   including the building being torn down (20 of 20 clean captured destroys).
//! * **Finishing a placement** clears the building site(s) it stands on, and
//!   each newly cleared site pays `lotPoints[district][k]` town XP, k being how
//!   many sites the district had cleared before it. A cleared site stays
//!   cleared: rebuilding on it pays no site points again, and destroying never
//!   takes XP back.
//! * **The town-level gate** for building or upgrading TO level L in style S is
//!   `styles[S].requireTownLevel[L]` (report #287). The APK keeps it per style
//!   per level and nowhere else: a Workshop is town level 3 in Timber or Stone
//!   but 5 in Castle. `building_upgrades.json` had one number per level (the
//!   first style's — Castle's, for a Workshop) and the server took the max of
//!   that and a hand-authored style value, so every Workshop asked for 5 and a
//!   level-3 town that the build menu offered one got a 409.

use std::collections::HashMap;
use std::sync::OnceLock;

use serde::Deserialize;
use serde_json::Value;
use uuid::Uuid;

static RAW: &str = include_str!("building_construction.json");

/// One building type's APK arrays. See the module doc for the indexing.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct BuildingConstruction {
    pub lot_size: u64,
    /// `"house"` for the three house types, the type's own id otherwise.
    pub family: String,
    /// Whether finishing one clears the building site under it. False for
    /// walls, the main gate, ruins and empty-lot markers — retail's sites under
    /// those stay `false` in every captured town.
    pub clears_lots: bool,
    pub building_limit: u64,
    pub construction_gold: Vec<u64>,
    pub construction_ms: Vec<u64>,
    pub upgrade_gold: Vec<u64>,
    pub upgrade_ms: Vec<u64>,
    pub destruction_gold: Vec<u64>,
    /// Per style: the `_styles[j]._levels[k]` values, indexed by level.
    #[serde(default)]
    pub styles: HashMap<Uuid, StyleLevels>,
}

/// One style's per-level rows. The extractor also writes `prestigeForLevel` /
/// `prestigeForStyle` beside these; the server does not read them (prestige is
/// still paid from `building_upgrades.json` and the measured
/// `style_prestige.json`; the level prestige agrees with the APK for every
/// shop / house / town hall row, and the style prestige agrees with every
/// measured restyle the server pays).
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct StyleLevels {
    pub require_town_level: Vec<u64>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct ConstructionData {
    /// Town XP for the k-th building site cleared, per district id.
    pub lot_points: HashMap<Uuid, Vec<u64>>,
    pub buildings: HashMap<Uuid, BuildingConstruction>,
}

/// The embedded table. A table that failed to parse would leave every building
/// on the `building_upgrades.json` fallback rather than panic a request; the
/// tests below pin that it parses and carries what the rules need.
pub(crate) fn data() -> &'static ConstructionData {
    static TABLE: OnceLock<ConstructionData> = OnceLock::new();
    TABLE.get_or_init(|| {
        serde_json::from_str(RAW).unwrap_or_else(|_| ConstructionData {
            lot_points: HashMap::new(),
            buildings: HashMap::new(),
        })
    })
}

/// `v[i]`, or the last entry past the end. The arrays run to the building limit
/// (32/33 entries); clamping only matters for a town already over it.
fn at_or_last(v: &[u64], i: u64) -> Option<u64> {
    v.get(i as usize).or(v.last()).copied()
}

impl BuildingConstruction {
    /// `(gold, ms)` to place one while `n` of its family already stand.
    pub fn placement(&self, n: u64) -> Option<(u64, u64)> {
        Some((
            at_or_last(&self.construction_gold, n)?,
            at_or_last(&self.construction_ms, n)?,
        ))
    }

    /// `(gold, ms)` to upgrade to `level`. Exact index only: a level the APK
    /// has no row for is left to the `building_upgrades.json` row.
    pub fn upgrade(&self, level: u64) -> Option<(u64, u64)> {
        let i = level as usize;
        Some((*self.upgrade_gold.get(i)?, *self.upgrade_ms.get(i)?))
    }

    /// Town level needed to build/upgrade TO `level` in `style`. Exact index
    /// only: a style or level the APK has no row for returns `None`, and the
    /// caller falls back to `building_upgrades.json`.
    pub fn require_town_level(&self, style: Uuid, level: u64) -> Option<u64> {
        self.styles
            .get(&style)?
            .require_town_level
            .get(level as usize)
            .copied()
    }

    /// Gold to destroy one while `n` of its family stand, itself included.
    pub fn destruction(&self, n: u64) -> Option<u64> {
        at_or_last(&self.destruction_gold, n)
    }
}

impl ConstructionData {
    pub fn building(&self, type_id: Uuid) -> Option<&BuildingConstruction> {
        self.buildings.get(&type_id)
    }

    fn family_of(&self, type_id: Uuid) -> String {
        self.building(type_id)
            .map(|b| b.family.clone())
            .unwrap_or_else(|| type_id.to_string())
    }
}

fn type_of(building: &Value) -> Option<Uuid> {
    building
        .get("typeId")
        .and_then(Value::as_str)
        .and_then(|s| Uuid::parse_str(s).ok())
}

fn style_of(building: &Value) -> Option<Uuid> {
    building
        .get("styleId")
        .and_then(Value::as_str)
        .and_then(|s| Uuid::parse_str(s).ok())
}

/// Every building object in the town, across districts and segments.
fn all_buildings(town: &Value) -> impl Iterator<Item = &Value> {
    town.get("districts")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(|d| d.get("segments").and_then(Value::as_object))
        .flat_map(|segs| segs.values())
        .filter_map(|s| s.get("buildings").and_then(Value::as_object))
        .flat_map(|b| b.values())
}

/// How many buildings of `type_id`'s family stand in the town, in any state
/// (one still under construction counts — retail's 18th consecutive house
/// placement priced at index 17 while the previous 17 were all still building).
pub(crate) fn family_count(town: &Value, type_id: Uuid) -> u64 {
    let data = data();
    let family = data.family_of(type_id);
    all_buildings(town)
        .filter_map(type_of)
        .filter(|t| data.family_of(*t) == family)
        .count() as u64
}

fn count_cleared(segments: &serde_json::Map<String, Value>) -> u64 {
    segments
        .values()
        .filter_map(|s| s.get("lotsCleared").and_then(Value::as_array))
        .flatten()
        .filter(|v| v.as_bool() == Some(true))
        .count() as u64
}

/// Mark sites `[start, start+size)` of one segment cleared, paying
/// `points[*n_cleared]` for each that was not, and advancing `n_cleared`.
/// Returns `None` when every one of those sites was already cleared.
fn clear_range(
    seg: &mut Value,
    start: u64,
    size: u64,
    points: &[u64],
    n_cleared: &mut u64,
) -> Option<u64> {
    let obj = seg.as_object_mut()?;
    let lots = obj
        .entry("lotsCleared".to_string())
        .or_insert_with(|| Value::Array(vec![Value::Bool(false); (start + size) as usize]))
        .as_array_mut()?;
    let mut paid = 0u64;
    let mut any = false;
    for i in start..start + size {
        let Some(slot) = lots.get_mut(i as usize) else {
            continue;
        };
        if slot.as_bool() == Some(true) {
            continue;
        }
        *slot = Value::Bool(true);
        // A site past the end of the table pays nothing rather than a guess.
        paid += points.get(*n_cleared as usize).copied().unwrap_or(0);
        *n_cleared += 1;
        any = true;
    }
    any.then_some(paid)
}

/// Clear the site(s) under `building_id` as its placement finishes, returning
/// the town XP the newly cleared sites pay. `0` when the type does not clear
/// sites or they were all cleared already (a rebuild on an old site).
pub(crate) fn clear_sites_for(town: &mut Value, building_id: Uuid) -> u64 {
    let data = data();
    let bid = building_id.to_string();
    let Some(districts) = town.get_mut("districts").and_then(Value::as_array_mut) else {
        return 0;
    };
    for district in districts {
        let district_id = district
            .get("id")
            .and_then(Value::as_str)
            .and_then(|s| Uuid::parse_str(s).ok());
        let Some(segments) = district.get_mut("segments").and_then(Value::as_object_mut) else {
            continue;
        };
        let found = segments.iter().find_map(|(key, seg)| {
            let b = seg.get("buildings")?.get(&bid)?;
            let start = b.get("startIndex").and_then(Value::as_u64).unwrap_or(0);
            Some((key.clone(), type_of(b), start))
        });
        let Some((key, type_id, start)) = found else {
            continue;
        };
        let Some(spec) = type_id
            .and_then(|t| data.building(t))
            .filter(|b| b.clears_lots)
        else {
            return 0;
        };
        let points = district_id
            .and_then(|d| data.lot_points.get(&d))
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        let mut n_cleared = count_cleared(segments);
        let Some(seg) = segments.get_mut(&key) else {
            return 0;
        };
        return clear_range(seg, start, spec.lot_size, points, &mut n_cleared).unwrap_or(0);
    }
    0
}

/// One-time correction for towns built before the site rules existed.
///
/// Our server used to pay a finished placement only its level's
/// `prestigeForLevel` and never marked a site cleared. For every standing
/// building whose placement has finished and whose site(s) are not yet
/// cleared, this pays what was missed — the style's level-0 prestige
/// (`style_prestige0(type, style)`) plus the site points — and clears the
/// sites, numbering them after the sites the district already had cleared.
///
/// Buildings on already-cleared sites (a town transferred from retail, or one
/// this has already run on) pay nothing, so it is idempotent on its own; the
/// caller still records that it ran. It cannot see buildings that were built
/// and later destroyed, so a town that churned buildings is under-credited by
/// their sites — the documented, accepted shortfall.
///
/// A placement still under construction (level 0, not `NORMAL`) is skipped:
/// finishing it pays its own way under the new rules.
pub(crate) fn backfill_sites(
    town: &mut Value,
    mut style_prestige0: impl FnMut(Uuid, Option<Uuid>) -> u64,
) -> u64 {
    let data = data();
    let mut grant = 0u64;
    let Some(districts) = town.get_mut("districts").and_then(Value::as_array_mut) else {
        return 0;
    };
    for district in districts {
        let district_id = district
            .get("id")
            .and_then(Value::as_str)
            .and_then(|s| Uuid::parse_str(s).ok());
        let points = district_id
            .and_then(|d| data.lot_points.get(&d))
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        let Some(segments) = district.get_mut("segments").and_then(Value::as_object_mut) else {
            continue;
        };
        let mut n_cleared = count_cleared(segments);
        for seg in segments.values_mut() {
            let mut placed: Vec<(u64, u64, Uuid, Option<Uuid>)> = seg
                .get("buildings")
                .and_then(Value::as_object)
                .into_iter()
                .flat_map(|m| m.values())
                .filter_map(|b| {
                    let type_id = type_of(b)?;
                    let spec = data.building(type_id).filter(|s| s.clears_lots)?;
                    let level = b.get("level").and_then(Value::as_u64).unwrap_or(0);
                    let state = b.get("state").and_then(Value::as_str).unwrap_or("NORMAL");
                    if level == 0 && state != "NORMAL" {
                        return None;
                    }
                    let start = b.get("startIndex").and_then(Value::as_u64).unwrap_or(0);
                    Some((start, spec.lot_size, type_id, style_of(b)))
                })
                .collect();
            placed.sort_by_key(|p| p.0);
            for (start, size, type_id, style_id) in placed {
                if let Some(paid) = clear_range(seg, start, size, points, &mut n_cleared) {
                    grant += paid + style_prestige0(type_id, style_id);
                }
            }
        }
    }
    grant
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    const DISTRICT: &str = "9a12c0d3-218c-4ef2-b78c-b6e3bca60719";
    const TOWN_HALL: &str = "a6a2de53-d65c-445a-8b55-d2a73c15b635";
    const FORGE: &str = "26fdb92f-a4df-4928-a97b-dee8699af605";
    const HOUSE_A: &str = "597f678f-b49e-4559-96a8-266aafeca6ad";
    const HOUSE_B: &str = "bfd7213e-b988-4237-8847-5e65e898f011";
    const HOUSE_C: &str = "c2edca96-f1d6-4867-b212-e7ff81517436";
    const WALL: &str = "52291bce-3585-49e5-85e4-afbdfa5ba422";

    fn u(s: &str) -> Uuid {
        Uuid::parse_str(s).unwrap()
    }

    #[test]
    fn the_embedded_table_parses_and_carries_every_rule_input() {
        let d = data();
        assert_eq!(
            d.buildings.len(),
            25,
            "every BuildingConstructionDataList template"
        );
        let pts = &d.lot_points[&u(DISTRICT)];
        assert_eq!(pts.len(), 36);
        assert_eq!(&pts[..4], &[25, 88, 150, 213]);
        assert_eq!(*pts.last().unwrap(), 2213);
        let forge = d.building(u(FORGE)).unwrap();
        assert_eq!((forge.lot_size, forge.building_limit), (2, 2));
        assert!(forge.clears_lots);
        assert!(
            !d.building(u(WALL)).unwrap().clears_lots,
            "walls never clear a site"
        );
        for h in [HOUSE_A, HOUSE_B, HOUSE_C] {
            let b = d.building(u(h)).unwrap();
            assert_eq!(
                (b.family.as_str(), b.lot_size, b.building_limit),
                ("house", 1, 32)
            );
        }
    }

    /// The APK arrays where `building_upgrades.json` had drifted (the known
    /// mismatches) — pinned so a regeneration that loses them fails here.
    #[test]
    fn upgrade_rows_are_the_apk_arrays() {
        let d = data();
        let get = |t: &str, l: u64| d.building(u(t)).unwrap().upgrade(l).unwrap();
        assert_eq!(get(HOUSE_B, 1), (3750, 1_200_000));
        assert_eq!(get(HOUSE_B, 2), (15_000, 1_800_000));
        assert_eq!(get(HOUSE_C, 1), (3750, 1_500_000));
        assert_eq!(get(HOUSE_C, 2), (15_000, 2_280_000));
        assert_eq!(
            get("e1dd10fc-8b14-4288-9b23-99b0d58388de", 1),
            (3400, 1_500_000),
            "AlchemistShop L1"
        );
        assert_eq!(get(FORGE, 8).0, 175_395, "Forge L8 gold");
        assert_eq!(get(FORGE, 1), (1040, 1_200_000));
        assert!(
            d.building(u(FORGE)).unwrap().upgrade(10).is_none(),
            "no row past the array"
        );
    }

    fn seg(id: &str, lots: usize, buildings: Value) -> (String, Value) {
        (
            id.to_string(),
            json!({ "id": id, "lotsCleared": vec![false; lots], "buildings": buildings }),
        )
    }

    fn bld(id: &str, type_id: &str, start: u64, level: u64, state: &str) -> (String, Value) {
        (
            id.to_string(),
            json!({
                "id": id, "typeId": type_id, "styleId": "aa133662-053d-434e-8779-3f2a41d1271e",
                "level": level, "startIndex": start, "state": state,
            }),
        )
    }

    fn town(segs: Vec<(String, Value)>) -> Value {
        let segments: serde_json::Map<String, Value> = segs.into_iter().collect();
        json!({
            "levelInfo": { "level": 0, "experiencePoints": 0 },
            "districts": [{ "id": DISTRICT, "segments": segments }]
        })
    }

    fn one(b: (String, Value)) -> Value {
        Value::Object([b].into_iter().collect())
    }

    #[test]
    fn houses_count_as_one_family_and_shops_each_their_own() {
        let mut segs = Vec::new();
        for i in 0..10 {
            let ty = [HOUSE_A, HOUSE_B, HOUSE_C][i % 3];
            let state = if i % 2 == 0 { "NORMAL" } else { "BUILDING" };
            segs.push(seg(
                &format!("s{i}"),
                1,
                one(bld(&format!("h{i}"), ty, 0, 0, state)),
            ));
        }
        segs.push(seg("f", 2, one(bld("f1", FORGE, 0, 3, "NORMAL"))));
        let t = town(segs);
        assert_eq!(
            family_count(&t, u(HOUSE_A)),
            10,
            "any state, all three house types"
        );
        assert_eq!(family_count(&t, u(FORGE)), 1);
        assert_eq!(
            family_count(&t, u("e1dd10fc-8b14-4288-9b23-99b0d58388de")),
            0
        );
        // Retail: a Castle House A placed with 10 houses standing paid 24,425 =
        // constructionGold[10] 21,425 + the Castle's 3,000.
        let (gold, ms) = data().building(u(HOUSE_A)).unwrap().placement(10).unwrap();
        assert_eq!((gold + 3000, ms), (24_425, 18_300_000));
    }

    #[test]
    fn finishing_a_placement_clears_its_sites_and_pays_the_next_points() {
        let id = |n: &str| bid(n).to_string();
        let mut t = town(vec![
            seg("th", 1, one(bld(&id("th"), TOWN_HALL, 0, 0, "BUILDING"))),
            seg("f", 2, one(bld(&id("f1"), FORGE, 0, 0, "BUILDING"))),
            seg("w", 1, one(bld(&id("w"), WALL, 0, 0, "NORMAL"))),
        ]);
        assert_eq!(
            clear_sites_for(&mut t, Uuid::from_u128(1)),
            0,
            "unknown building"
        );
        assert_eq!(clear_sites_for(&mut t, bid("th")), 25, "first site");
        assert_eq!(
            clear_sites_for(&mut t, bid("f1")),
            88 + 150,
            "a shop clears two"
        );
        assert_eq!(
            clear_sites_for(&mut t, bid("f1")),
            0,
            "cleared stays cleared"
        );
        assert_eq!(
            clear_sites_for(&mut t, bid("w")),
            0,
            "walls never clear a site"
        );
        let segs = &t["districts"][0]["segments"];
        assert_eq!(segs["f"]["lotsCleared"], json!([true, true]));
        assert_eq!(segs["w"]["lotsCleared"], json!([false]));
    }

    fn bid(name: &str) -> Uuid {
        // `bld` ids are plain strings; give the tests uuids that round-trip.
        let mut t = String::from("00000000-0000-0000-0000-");
        let hex: String = name.bytes().map(|b| format!("{b:02x}")).collect();
        t.push_str(&format!("{hex:0>12}"));
        Uuid::parse_str(&t).unwrap()
    }

    #[test]
    fn the_backfill_pays_site_points_and_style_prestige_once() {
        let id = |n: &str| bid(n).to_string();
        let mut t = town(vec![
            seg("th", 1, one(bld(&id("th"), TOWN_HALL, 0, 0, "NORMAL"))),
            seg("f1", 2, one(bld(&id("f1"), FORGE, 0, 2, "NORMAL"))),
            seg("f2", 2, one(bld(&id("f2"), FORGE, 0, 1, "UPGRADING"))),
            seg(
                "hh",
                2,
                Value::Object(
                    [
                        bld(&id("h1"), HOUSE_A, 0, 0, "NORMAL"),
                        bld(&id("h2"), HOUSE_B, 1, 1, "NORMAL"),
                    ]
                    .into_iter()
                    .collect(),
                ),
            ),
            // Still being placed: finishing it pays its own way, so not here.
            seg("hb", 1, one(bld(&id("h3"), HOUSE_C, 0, 0, "BUILDING"))),
            seg("w", 1, one(bld(&id("w"), WALL, 0, 0, "NORMAL"))),
        ]);
        let mut styled = 0;
        let grant = backfill_sites(&mut t, |_, s| {
            assert!(s.is_some());
            styled += 1;
            10
        });
        // Town Hall 1 + Forges 2 + 2 + houses 1 + 1 = 7 sites: 25+88+150+213+275+338+400.
        assert_eq!(styled, 5, "one style payment per finished placement");
        assert_eq!(grant, 1489 + 5 * 10);
        assert_eq!(
            t["districts"][0]["segments"]["hb"]["lotsCleared"],
            json!([false])
        );
        assert_eq!(
            t["districts"][0]["segments"]["w"]["lotsCleared"],
            json!([false])
        );
        assert_eq!(
            backfill_sites(&mut t, |_, _| 10),
            0,
            "idempotent on its own"
        );
    }

    /// A town that came over from retail already has its sites cleared and was
    /// paid for them there.
    #[test]
    fn the_backfill_pays_nothing_for_sites_retail_already_cleared() {
        let mut t = town(vec![seg(
            "f",
            2,
            one(bld(&bid("f").to_string(), FORGE, 0, 4, "NORMAL")),
        )]);
        t["districts"][0]["segments"]["f"]["lotsCleared"] = json!([true, true]);
        assert_eq!(backfill_sites(&mut t, |_, _| 99), 0);
    }
}
